// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StudentPortal.Entity
{
    public partial class ExcelStudentMarksDb
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(20)]
        public string Student_RollNo { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Name { get; set; }
        public int Tamil { get; set; }
        public int English { get; set; }
        public int Maths { get; set; }
        public int Science { get; set; }
        public int Social { get; set; }
        public int Total_Marks { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
        public bool Is_Deleted { get; set; }
    }
}