// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StudentPortal.Entity
{
    public partial class StaffLoginDetailsDb
    {
        [Key]
        public int Staff_User_Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Staff_User_Name { get; set; }
        [Required]
        [StringLength(20)]
        public string Staff_Password { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Inserted_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
        public bool Is_Deleted { get; set; }
    }
}