// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StudentPortal.Entity
{
    public partial class StudentExcelDb
    {
        [Key]
        public int Student_Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_First_Name { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Roll_No { get; set; }
        [Required]
        [StringLength(30)]
        public string English { get; set; }
        [Required]
        [StringLength(30)]
        public string Maths { get; set; }
        [Required]
        [StringLength(30)]
        public string Sciences { get; set; }
        [Required]
        [StringLength(30)]
        public string Total { get; set; }
        [StringLength(30)]
        public string Average { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Inserted_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
        public bool Is_Deleted { get; set; }
    }
}