// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StudentPortal.Entity
{
    public partial class StudentDb
    {
        [Key]
        public int Student_Id { get; set; }
        public int Student_Roll_No { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_First_Name { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Last_Name { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Gender { get; set; }
        [Column(TypeName = "date")]
        public DateTime Student_DateOfBrith { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Father_First_Name { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Father_Last_Name { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Mother_Fisrt_Name { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Mother_Last_Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Student_Email_Id { get; set; }
        public long Student_Contact_No { get; set; }
        public long Student_Father_Contact_No { get; set; }
        [Required]
        [StringLength(30)]
        public string Father_Occupation { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Password { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Inserted_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
    }
}